### ISSUE TITLE
Send MKR Feature

### ISSUE THREAD

**Issue by kennyrowe** [MakerDAO/maker-otc#106]
I've been playing with the app with MetaMask and realized there isn't a user friendly to send MKR tokens on the interface. Metamask has a built in send ETH but not MKR.

**Comment by jorisbontje** [comment]
I inquired with @kumavis on the plans for adding EIP20 token support to MetaMask:

> Yep, they are in the designs, but not an immediate priority
> Tho End of theDao creation period is not far off
> It wont be hard to add we just have to tackle a few things first
