### ISSUE TITLE
Display Tokens as otc.ETH and otc.MKR

### ISSUE THREAD

**Issue by Riverhead** [MakerDAO/maker-otc#116]
When looking at the UI and seeing that I have x ETH and y ETH TOKENS and z MKR it's not easy to figure out how much funds I have where.

Suggestion: Rename the label for ETH TOKENS to something like otc.ETH so it's clear these are the ETH that are in the contract. MKR and otc.MKR can get the same treatment since it's not clear where the MKR are (in the contract, in my wallet, or a sum of both)

**Comment by jorisbontje** [comment]
Maybe :) There is only 1 MKR asset though; no MKR and otc.MKR.
