### ISSUE TITLE
Token Balances part of Allowance section

### ISSUE THREAD

**Issue by Riverhead** [MakerDAO/maker-otc#118]
Suggestion: Remove the Tokens balances from the top and move them down to the allowance section and display allowance as x of y. **Bonus points**: Have a slider to set the allowance between 0 and token-balance.

Allowance: 
ETH 0 -------------- |99| ------------- 198

MKR 0 -----------------------|38| ----- 42

**Comment by jorisbontje** [comment]
Drawback with this is that you can have an allowance that exceeds your token balance; this will be hard / impossible to set with a slider.

**Comment by jorisbontje** [comment]
@cassiopaia could you try how this would work in your designs?

**Comment by cassiopaia** [comment]
https://github.com/MakerDAO/maker-otc/issues/118#issuecomment-219949788

we could make the right max vol as a changeable input (like the wallet names etc @eth wallet (mist))
