### ISSUE TITLE
Show more/all trades

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#125]
amans on slack requested the feature to show more trades from the history than just the last 10;
I can see two options for this:
1) we add a "Show more/all trades" link which removes the limit to the filter
2) we add an "export to CSV" and allow the user to download the raw data; not sure if this is possible to do client side.

**Comment by pimato** [comment]
in Poloniex they have both options and I use both of them. This implementation would be perfect!
