### ISSUE TITLE
Backwards compatibility of market contracts

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#129]
* [ ] Investigate if we can have multiple branches / releases on GitHub Pages
* [ ] Alternatively use Surge.sh for the same
* [ ] Indicate in the UI that there is a new version, but old versions can be found THERE
* [ ] Document and automate the release procedure

**Comment by nmushegian** [comment]
I don't see why we need different UI versions instead of evolving the UI and contracts separately. In any case, supporting old market orders in any updated UI is a very important, even if there are shinier order types or market addresses available.

**Comment by jorisbontje** [comment]
@nmushegian that doesn't seem to be in line with the "widget" approach that you have previously suggested for the contract user interface. Supporting multiple contracts, staying in sync with them and trading on the best prices available will cause quite some complexity and (startup) overhead for light browser clients that aren't always-on. Instead I would suggest to have keeper tasks monitor multiple market (versions) and handle arbitrage opportunities.

**Comment by nmushegian** [comment]
Ok I'm convinced this is fine, at least for now.
