### ISSUE TITLE
dapp (testnet) deployment on public site

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#13]
Trying to install on Heroku with https://github.com/AdmitHub/meteor-buildpack-horse
Alternative approach would be to use https://github.com/frozeman/meteor-build-client and deploy the static file anywhere
Host on Github Pages: https://pages.github.com/

Depending on issue:
* [ ] https://github.com/nexusdev/dapple/issues/228 dapple build TypeError: Cannot read property 'ignore' of undefined

**Comment by ryepdx** [comment]
It should't be necessary to do a `dapple build` on the server. The build output is just a static file.

It might be interesting to distribute the frontend via IPFS as a flat HTML file with all resources embedded. I've already set up a Gulp workflow for creating such files as a part of building http://github.com/ryepdx/ethaddress.org which might be useful, if you want to take a look and get a feeling for what'd be involved.

**Comment by ryepdx** [comment]
Sorry, accidentally hit "close and comment."
