### ISSUE TITLE
Create deployment checklist

### ISSUE THREAD

**Issue by jorisbontje** [makerdao/maker-otc#142]
- how to configure & run
- enable optimize 
- how to verify contract on etherscan.io

**Comment by sunfeld** [comment]
Maybe a readme for contract deployment is also a helpful thing.
I was facing some difficulty when deploying the expiring market and made the following readme:

**Deploying a contract**

Make sure you have a ".dapplerc" file in your home directory to load the settings for different environments.

Examples and documentation on the format of the .dapplerc file: http://dapple.readthedocs.io/en/master/dapplerc/

At the root of the project run: `dapple test` to check the deployment of contracts in the internal evm.

To deploy a contract use a ".ds" deployment script in the "scripts" folder.
Run: `dapple run scripts/deploy_expiring_market.ds -e morden` where the `-e` option defines the environment to use.

After a succesful deployment run: `gulp build`

You are now able to do run the meteor frontend.
