### ISSUE TITLE
does not compile with Solidity >= 0.4.0

### ISSUE THREAD

**Issue by SCBuergel** [makerdao/maker-otc#148]
The empty modifier

```
    modifier can_offer {
        _
    }
```

in https://github.com/makerdao/maker-otc/blob/master/contracts/simple_market.sol
does not compile, just checked in Ethereum Studio and also using the online compiler https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.3+commit.2353da71.js

```
maker-otc/contracts/simple_market.sol:37:5: Error: Expected token Semicolon got 'RBrace'
```

I actually do not see the point in that empty modifier, why not just delete it?

**Comment by SCBuergel** [comment]
Actually I just realized that since Solidity 0.4.0 we need a semicolon behind the underscore: https://github.com/ethereum/solidity/releases/tag/v0.4.0

I suggest to make all modifiers compatible with those newer versions of solidity and also add a `pragma solidity` in all files for the version.

**Comment by rainbeam** [comment]
@SCBuergel: see https://github.com/makerdao/maker-otc/pull/147
