### ISSUE TITLE
use separate events per function in SimpleMarket

### ISSUE THREAD

**Issue by SCBuergel** [makerdao/maker-otc#152]
We should have separate events for `offer`, `buy`, `cancel`, `trade`, instead of reusing `ItemUpdate` in [SimpleMarket](https://github.com/makerdao/maker-otc/blob/master/contracts/simple_market.sol).

**Comment by nmushegian** [comment]
https://github.com/makerdao/maker-otc/pull/155

**Comment by gbalabasquer** [comment]
Closing this issue. We have separate events since a long time ago.
