### ISSUE TITLE
Offers can be created on testnet even if there are no funds.

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#16]
Deployed on Morden:
```
DEPLOYED: AtomicTradeMorden = 0x566bced2e7dd50064c94012e1c008ffb9bf24ba6
```

With this contract I can create offers even if I don't have (sufficient) MKR, ETH, DAI funds. Also when I do have enough it isn't taken from my account.

I would expect that the `transferFrom` in the `offer` function would debit my accounts or `throw` if I have insufficient funds. However the offer is created and persisted in the orderbook without error or changing my funds.

**Comment by nmushegian** [comment]
Are you sure this isn't the version where the transfers were all commented out in your last working branch?  https://github.com/MakerDAO/maker-otc/pull/3/files

**Comment by jorisbontje** [comment]
Yeah, very sure.

on `testnet`:
```
> eth.getCode('0x566bced2e7dd50064c94012e1c008ffb9bf24ba6').length
5870
> web3.sha3(eth.getCode('0x566bced2e7dd50064c94012e1c008ffb9bf24ba6'), true)
"0bb4761967119ac546e49857c0f4248154ce7507eb193813e11296e8ed1a9369"
```

verifying the source code of https://raw.githubusercontent.com/MakerDAO/maker-otc/master/contracts/atomic_trade.sol
```
$ shasum contracts/atomic_trade.sol
36838899cc612aead56754f9f7ff1fa0e6eaf3a7  contracts/atomic_trade.sol
```

now deploying that on devnet:
```
$ dapple run scripts/deploy_morden.ds
Using local solc installation...
simulated successfully
Deploying to environment "default"...
Connected to RPC client, block height is 33
DEPLOYED: AtomicTradeMorden = 0x456e351ba3bfea7b027f55131b53371473b52cec
GAS COST: 824888 for "new AtomicTradeMorden"
CONFIRMED deploy after 1 blocks!
```

```
> eth.getCode('0x456e351ba3bfea7b027f55131b53371473b52cec').length
5870
> web3.sha3(eth.getCode('0x456e351ba3bfea7b027f55131b53371473b52cec'), true)
"0bb4761967119ac546e49857c0f4248154ce7507eb193813e11296e8ed1a9369"
```

which matches the length and hash on testnet

**Comment by nmushegian** [comment]
Ok, here we can see that the token registry is set to address(0x1):  https://morden.ether.camp/account/566bced2e7dd50064c94012e1c008ffb9bf24ba6

This revealed a serious MakerUser bug:  https://github.com/MakerDAO/maker-user/blob/c4231781bfde5e06f4824d88d2a7345eb17c1478/contracts/user.sol

`registry` is just an argument, not the actual registry! (called `_M`)

**Comment by nmushegian** [comment]
https://github.com/MakerDAO/maker-user/releases

**Comment by ryepdx** [comment]
Just updated the `dapple_packages` submodules and bumped the dependency versions in the dappfile, so resolving this should just be a matter of a redeploy. Will edit this comment once I get a chance to run the deploy scripts.

**Comment by ryepdx** [comment]
Okay, I'm taking the silence as confirmation that this issue has been resolved. Closing now!
