### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by cassiopaia** [MakerDAO/maker-otc#19]

**Comment by jorisbontje** [comment]
@cassiopaia Do you have an update on this?

**Comment by cassiopaia** [comment]
will update this week, sry for delay :/

**Comment by jorisbontje** [comment]
Latest design by @cassiopaia ![bildschirmfoto 2016-05-18 um 18 24 24](https://cloud.githubusercontent.com/assets/620959/15419419/1d0840b0-1e66-11e6-8901-5842c2b0bfdf.png)

**Comment by jorisbontje** [comment]
some minor points:
* [ ] use 2 dropdowns for selecting market pairs (this is already in the next version)
* [ ] orderbook should have 3 columns: Price, MKR, ETH… or maybe more (cumulative total?)?
* [ ] buy/sell dropdown should be under NEW ORDER panel

**Comment by pimato** [comment]
hey, I would love to help here, Is it possible to get the psd, so I can change the things jorisbontje wanted to change here ? I really want to do something. Have a lot experience in UX Design especially in Android(Material Design) and done some Gamedesign. I would do anything .

**Comment by nmushegian** [comment]
@pimato PM me on rocket chat chat.makerdao.com
