### ISSUE TITLE
remove "for MKR" from header tagline

### ISSUE THREAD

**Issue by nmushegian** [MakerDAO/maker-otc#23]
If anything, the focus of otc should be Dai, not maker. But I think the tagline should just be "Simple on-chain trading" or something.

**Comment by jorisbontje** [comment]
Removed from the UI, still needs to be removed form the README header: https://github.com/MakerDAO/maker-otc/blob/master/README.md

**Comment by nmushegian** [comment]
@cassiopaia  ?

**Comment by cassiopaia** [comment]
https://github.com/MakerDAO/maker-otc/commit/b8951754c17e4d9311e3bd8a83c8eeb66e269156
https://github.com/MakerDAO/maker-otc/commit/9b5fb1cae015e69ea4eb1a0f50a26f53b01e0127

**Comment by nmushegian** [comment]
It still says "for MKR" @cassiopaia 
https://ipfs.pics/ipfs/QmYyqTEebLaBaCnQpDH7q8JSNuzvSWrVsWPA4SCbPi2u5L
