### ISSUE TITLE
Contract method input validation

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#26]
The current contract methods lack input validations on:
- buy / sell price
- buy / sell quantity
- ids
- tokens

With this it is possible to create an offer with a price or amount of zero, which could result in division by zeroes, spam in the orderbook an useless events.

I would suggest minimal input validation (values to be > 0, etc) and do a `throw` in case of invalid input.

**Comment by ryepdx** [comment]
Resolved with f28203f9d9530d21ea9e6b282a5e6cab03b51ae0
