### ISSUE TITLE
Investigate MetaMask compatibility

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#41]
https://metamask.io/

* [x] Maker-OTC asynchronous web3 calls #42
* [x] Maker-JS Asynchronous web3.eth calls https://github.com/MakerDAO/maker-js/issues/9

**Comment by kumavis** [comment]
hi! let us know how we can help!
cc @flyswatter

**Comment by kumavis** [comment]
Here's the WIP compatibility guide https://github.com/MetaMask/compat-guide/

**Comment by jorisbontje** [comment]
Added account sync interval

**Comment by flyswatter** [comment]
That’s a good pattern, and I don’t think we’ve actually added it to the compatibility guide yet!

I’ll add it over soon!

**Comment by kumavis** [comment]
@jorisbontje any remaining issues here? besides the tx notification when popup is locked?

**Comment by jorisbontje** [comment]
No other known issues, though didnt check much with the jsonrpc server
being down.
