### ISSUE TITLE
All web3 calls to be asynchronous

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#42]
we'll need this for MetaMask support

**Comment by kumavis** [comment]
metamask can correctly handle synchronous `eth_accounts` and `eth_coinbase`. thats about it.

**Comment by jorisbontje** [comment]
@kumavis am I correct to think that only `web3.eth` calls need to be asynchronous? or also other ones outside of the `.eth` namespace?

**Comment by kumavis** [comment]
all json rpc calls, not web3 utility methods like `toWei`

**Comment by jorisbontje** [comment]
Problematic code:

`web3.isConnected()` calls in `client/lib/init.js`; there is no asynchronous version for this in web3:
https://github.com/ethereum/web3.js/issues/440
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3isconnected

**Comment by jorisbontje** [comment]
Closed via #99
