### ISSUE TITLE
Support partial orders in frontend

### ISSUE THREAD

**Issue by rainbeam** [MakerDAO/maker-otc#46]
Backend allows partial fills but frontend doesn't.

**Comment by jorisbontje** [comment]
Comments on this by Vitalik on [Reddit]( https://www.reddit.com/r/ethtrader/comments/4gkc1h/simple_onchain_otc_market_alpha_release/d2j3rxn):
> Later on, let people partially fill orders. Also, in the interface group identically priced orders from multiple users together.
