### ISSUE TITLE
orderbook entry format

### ISSUE THREAD

**Issue by rainbeam** [MakerDAO/maker-otc#47]
Current order book entry is `bid / value / volume`. I'm not finding that very intuitive to scan.

Alternative: `price / buy_how_much / sell_how_much`. This is the format that I'm used to from other exchanges.

---

Edit: Realise now that these formats are actually the same... just the value is denominated in DAI.

I think adding units onto the 'value' column would make it scan better.

**Comment by jorisbontje** [comment]
Comments on this by Vitalik on [Reddit]( https://www.reddit.com/r/ethtrader/comments/4gkc1h/simple_onchain_otc_market_alpha_release/d2j3rxn):
> Label the columns more clearly. I recommend "price" (ie. amount of currency B per unit of currency A) and "volume", specified in both currencies (eg. "0.10 MKR / 0.50 ETH")

**Comment by jorisbontje** [comment]
@rainbeam please review!
