### ISSUE TITLE
Log an event for (partial) trades

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#48]
When a (partial) trade gets accepted, a `Trade` event should be logged. This would allow for some essential market history in (light) clients. 

The `Trade` event should have the following attributes:
* `sell_how_much`
* `sell_which_token` (indexed?)
* `buy_how_much`
* `buy_which_token` (indexed?)

**Comment by rainbeam** [comment]
Implemented in #50. Other things that could be logged in the Trade event:

- seller address
- buyer address
- order id
- trade id (accounts for partials)
- timestamp (indexed)

N.B. maximum of three parameters can be indexed.

**Comment by jorisbontje** [comment]
Adding both `seller_address` and `buyer_address` might be good for filtering person trading history, but indexing both would exceed 3 indexes.

I don't think OrderID and TradeID adds much value for common use cases. The timestamp can be derived from the block number to which the transaction receipt is connected, so no need to track that individually.
