### ISSUE TITLE
fix basic LPC cost function

### ISSUE THREAD

**Issue by nmushegian** [MakerDAO/maker-otc#5]
`buyCost` should be changed to compute the fee based on the last time that someone placed an order. The fee rate is an increasing function w.r.t. purchased quantity (defined by slope). The real fee charged is the integral of the fee rate at the last time through the fee rate at the current time. The fee rate decreases to 0 linearly over time - this is also prorated before the other calculations.

**Comment by ryepdx** [comment]
Any opinion on what slope should be used for the linear decrease toward zero?

**Comment by nmushegian** [comment]
Anything we make up will probably be wrong, so do the simplest thing that has the right sign so we can sanity check it before we research the correct solution

**Comment by jorisbontje** [comment]
I wouldn't consider this to be critical for the `mvp` milestone.

**Comment by nmushegian** [comment]
I think ran can fix the LPC cost function fast compared to the rest of the work required for LPC function. Whether or LPCs are in scope at all is up to you

**Comment by nmushegian** [comment]
closing in favor of https://github.com/MakerDAO/maker-otc/issues/71
