### ISSUE TITLE
Detect network sync status based on last block timestamp

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#61]
If the timestamp of the most recent block is > 60 seconds old, the network is very likely not in sync. In that we case we should show that in the network status.

This prevents the network from being indicated as ready, while the geth process hasn't started syncing yet.

**Comment by hitchcott** [comment]
FYI, https://github.com/ethereum/web3.js/issues/376

I'm sure you know already that timestamps aren't bulletproof. Needs an idiomatic API in web3 if possible.
