### ISSUE TITLE
Build for meteor doesn't work here.

### ISSUE THREAD

**Issue by sjamayee** [MakerDAO/maker-otc#62]
Something with option --template meteor.

[npm-debug.log.txt](https://github.com/MakerDAO/maker-otc/files/232856/npm-debug.log.txt)

**Comment by jorisbontje** [comment]
From the stacktrace it isn't clear to me what fails exactly, can you try running `dapple build --template meteor --no-deploy-data` directly and report back what kind of errors you get?

Also be sure to verify that you have an up to date dapple version; 0.7.1 preferably: `dapple --version`

**Comment by sjamayee** [comment]
Not related to maker-dao.

**Comment by sjamayee** [comment]
There is something wrong with the build (dapple-build).
It writes the file "meteor.js"  into frontend/build
After I moved meteor.js into frontend/packages/dapple/build, then it worked.

iMac:maker-otc jac$ ls -al
total 88
drwxr-xr-x  20 jac  staff   680 Apr 24 18:14 .
drwxr-xr-x   4 jac  staff   136 Apr 23 10:18 ..
drwxr-xr-x  13 jac  staff   442 Apr 22 20:18 .git
-rw-r--r--   1 jac  staff   115 Apr 22 20:18 .gitignore
-rw-r--r--   1 jac  staff   351 Apr 22 20:18 .gitmodules
-rwxr-xr-x   1 jac  staff   230 Apr 22 20:18 .travis.dapple-docker-entry
-rw-r--r--   1 jac  staff    31 Apr 22 20:18 .travis.dapplerc
-rw-r--r--   1 jac  staff  1004 Apr 22 20:18 .travis.yml
-rw-r--r--   1 jac  staff  2816 Apr 22 20:18 README.md
drwxr-xr-x   5 jac  staff   170 Apr 24 14:27 build
drwxr-xr-x  10 jac  staff   340 Apr 22 20:18 contracts
-rw-r--r--   1 jac  staff   258 Apr 24 18:05 dappfile
drwxr-xr-x   5 jac  staff   170 Apr 22 20:18 dapple_packages
drwxr-xr-x   5 jac  staff   170 Apr 24 18:02 frontend
-rw-r--r--   1 jac  staff  1078 Apr 22 20:18 gulpfile.js
drwxr-xr-x   9 jac  staff   306 Apr 24 18:08 node_modules
-rw-r--r--   1 jac  staff  1590 Apr 24 18:14 npm-debug.log
-rw-r--r--   1 jac  staff  2989 Apr 23 10:19 npm-debug.log.txt
-rw-r--r--   1 jac  staff   951 Apr 22 20:55 package.json
drwxr-xr-x   5 jac  staff   170 Apr 22 20:18 scripts
iMac:maker-otc jac$ ls -al build
total 1176
drwxr-xr-x   5 jac  staff     170 Apr 24 14:27 .
drwxr-xr-x  20 jac  staff     680 Apr 24 18:14 ..
-rw-r--r--   1 jac  staff  443720 Apr 24 18:16 classes.json
drwxr-xr-x   3 jac  staff     102 Apr 24 14:27 environments
-rw-r--r--   1 jac  staff  151753 Apr 24 18:16 meteor.js
iMac:maker-otc jac$ ls -al frontend/packages/dapple/build
total 1968
drwxr-xr-x  6 jac  staff     204 Apr 24 18:22 .
drwxr-xr-x  7 jac  staff     238 Apr 22 20:43 ..
-rw-r--r--  1 jac  staff  442212 Apr 22 21:16 classes.json
drwxr-xr-x  4 jac  staff     136 Apr 22 20:43 environments
-rw-r--r--  1 jac  staff  408319 Apr 22 21:16 js_module.js
-rw-r--r--  1 jac  staff  151753 Apr 24 18:22 meteor.js
iMac:maker-otc jac$

**Comment by jorisbontje** [comment]
@ryepdx any clue what could cause this?

**Comment by jorisbontje** [comment]
@sjamayee are you on the Maker Slack? please drop by in #dapp-dev for real-time support on this issue :)

**Comment by jorisbontje** [comment]
Please re-open if you have additional information.

**Comment by eliooses** [comment]
I have this same issue.

![image](https://cloud.githubusercontent.com/assets/5062034/22393620/eb2b250e-e4e8-11e6-94df-59b6be0206fe.png)

My version of daaple is 0.8.39

Any help?

**Comment by jorisbontje** [comment]
looks like your dapple isnt initialized properly. try `dapple init`
