### ISSUE TITLE
Big fat disclaimer

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-otc#68]
Insert a big fat disclaimer in the UI.
MakerOTC is in test mode, dangerous & unsafe etc.

**Comment by Rune23** [comment]
How about
MakerOTC is undergoing alpha testing: Proceed at your own risk, and use only small amounts of ETH and MKR.

**Comment by jorisbontje** [comment]
Added. 6ed63fd06fd53507844ee7c872355f86fa7b9e7b
