### ISSUE TITLE
order matching keeper task

### ISSUE THREAD

**Issue by nmushegian** [MakerDAO/maker-otc#8]
Bot/ keeper task that connects to the exchange and performs (arbitrage) trades.

* [ ] Study https://github.com/nexusdev/keeper
* [ ] Discuss with dbrock how to integrate this with keeper

**Comment by jorisbontje** [comment]
Development for this is happening in https://github.com/BlockChainCompany/maker-market-matcher

**Comment by cassiopaia** [comment]
ported to new maker-market repo

https://github.com/MakerDAO/maker-market/issues/5
