### ISSUE TITLE
separate UI and contract repos. Keep contract type repos as submodules.

### ISSUE THREAD

**Issue by nmushegian** [MakerDAO/maker-otc#93]
thoughts? The UI build pipeline just needs to call dapple build on the submodules, then bundle it in whatever wrappers they decide. This way you can more carefully manage which version's build output you're using and the contract devs don't have to worry about breaking things

**Comment by rainbeam** [comment]
This makes sense for the individual market types as well (simple / lpc / btc), which could have their own repos. That said, submodules can be annoying to work with. I don't think we're complicated enough to need more than branches currently, but could see it getting to that stage at some point.

Thinking further ahead, do we even need submodules? Backend contract code can be deployed and versioned by address - then all the frontend needs is to change the address it talks to.

**Comment by nmushegian** [comment]
submodules are a nice intermediate solution until content-addressed dapple packages are online (via an on-chain registry or otherwise)

**Comment by jorisbontje** [comment]
Could a github admin please create a `maker-market` repository? Then we can start separating the UI from the Contracts and include them as submodule per Nikolai's suggestion.
